### ISSUE TITLE
Incorrect Mapping of scale factor and offset for MCP3208

### ISSUE THREAD

**Issue by github-kishan** [007-akash/WMS_Logger#1]
Hi,
There is incorrect mapping of offset and scale factor for mcp3208 as per the Modbus address space provided. When I update offset It got updated as scale in the configuration file and when I update scale over modbus it got updated as offset in configuration file.

**Comment by 007-akash** [comment]
Fixed in Commit "Fixed Issue 1 and Issue 2"
